redstone:
 red:
   x: 0
   y: 0
   z: 0
 blue:
   x: 0
   y: 0
   z: 0
 yellow:
   x: 0
   y: 0
   z: 0
 green:
   x: 0
   y: 0
   z: 0
performer: null
limitTime: 0
countDownDisplay: true